# generated by datamodel-codegen:
#   filename:  Accounts.yaml
#   timestamp: 2026-09-07T12:56:29+00:00

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, Field


class Conditions(BaseModel):
    type: str = Field(
        ..., description='Tipo de Condición', examples=['Límite'], max_length=40
    )
    description: str | None = Field(
        None,
        description='Descripción de la condición',
        examples=['Cargo mensual'],
        max_length=140,
    )
    amount: float | None = Field(
        None, description='Monto de la Condición', examples=['3000']
    )
    currency: str | None = Field(
        None,
        description='Moneda de la Condición',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )


class CurrentBalance(BaseModel):
    amount: float = Field(..., description='Monto del saldo', examples=['15000'])
    currency: str = Field(
        ...,
        description='Moneda del saldo',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )
    timestamp: AwareDatetime | None = Field(
        None, description='Fecha/hora del saldo', examples=['2025-02-20T10:00:00Z']
    )
    availableOverdraft: float | None = Field(
        None, description='Límite Sobregiro Disponible', examples=['200000']
    )
    holdAmount: float | None = Field(
        None, description='Monto Retenido', examples=['15000']
    )


class Balances(BaseModel):
    bookingDate: AwareDatetime = Field(
        ..., description='Fecha de registro', examples=['2025-01-10T00:00:00Z']
    )
    amount: str = Field(..., description='Monto del saldo', examples=['14000'])
    currency: str = Field(
        ..., description='Moneda Saldo', examples=['CLP'], max_length=3, min_length=3
    )
    averageBalance: float | None = Field(
        None, description='Saldo promedio', examples=['14500']
    )
    lockedAmount: float | None = Field(
        None, description='Monto bloqueado', examples=['2000']
    )
    lockedCurrency: str | None = Field(
        None,
        description='Moneda del monto bloqueado',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )


class CurrentOverdraftLimit(BaseModel):
    amount: float = Field(..., description='Monto del Sobregiro', examples=['200000'])
    currency: str = Field(
        ...,
        description='Moneda del Sobregiro',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )
    startDate: date | None = Field(
        None,
        description='Fecha de Inicio de Vigencia',
        examples=['2025-01-01'],
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )
    expiryDate: date | None = Field(
        None,
        description='Fecha de Expiración',
        examples=['2025-12-31'],
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )
    interestRate: float | None = Field(
        None, description='Tasa de Interés del Sobregiro', examples=[2.5]
    )
    usageAmount: float | None = Field(
        None, description='Monto Utilizado', examples=['550000']
    )
    usageCurrency: str | None = Field(
        None,
        description='Moneda del Monto Utilizado',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )


class OverdraftLimit(BaseModel):
    limitId: str = Field(
        ...,
        description='Identificador del Sobregiro',
        examples=['OD202501'],
        max_length=40,
    )
    amount: float = Field(..., description='Monto del Sobregiro', examples=['200000'])
    currency: str = Field(
        ...,
        description='Moneda del Sobregiro',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )
    startDate: date = Field(
        ...,
        description='Fecha de Inicio de Vigencia',
        examples=['2025-01-01'],
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )
    endDate: date | None = Field(
        None,
        description='Fecha fin de Vigencia',
        examples=['2025-12-31'],
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )
    interestRate: float | None = Field(
        None, description='Tasa de Interés del Sobregiro', examples=[2.5]
    )
    usageAmount: float | None = Field(
        None, description='Monto Utilizado', examples=['550000']
    )
    usageCurrency: str | None = Field(
        None,
        description='Moneda del Monto',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )


class MerchantDetails(BaseModel):
    name: str | None = Field(
        None,
        description='Nombre del comercio',
        examples=['Supermercado ABC'],
        max_length=140,
    )
    category: str | None = Field(
        None, description='Categoría', examples=['Alimentos'], max_length=70
    )


class Debtor(BaseModel):
    agent: str | None = Field(
        None, description='Identificador del deudor', examples=['Rut'], max_length=40
    )
    address: str | None = Field(
        None,
        description='Dirección del Deudor',
        examples=['Avenida providencia 345, Las Condes'],
        max_length=256,
    )
    account: str | None = Field(
        None, description='Cuenta del deudor', examples=['12345678-9'], max_length=256
    )


class CardInstrument(BaseModel):
    scheme: str = Field(
        ..., description='Marca de la tarjeta', examples=['Visa'], max_length=40
    )


class Creditor(BaseModel):
    agent: str | None = Field(
        None, description='Identificador del acreedor', examples=['Rut'], max_length=40
    )
    address: str | None = Field(
        None,
        description='Dirección del acreedor',
        examples=['Avenida providencia 345, Las Condes'],
        max_length=256,
    )
    account: str | None = Field(
        None, description='Cuenta del acreedor', examples=['12345678-9'], max_length=256
    )


class UltimateCreditor(BaseModel):
    name: str | None = Field(
        None,
        description='Identificador del acreedor final',
        examples=['Empresa XYZ'],
        max_length=140,
    )
    address: str | None = Field(
        None,
        description='Dirección del acreedor final',
        examples=['Avenida providencia 345, Las Condes'],
        max_length=256,
    )


class UltimateDebtor(BaseModel):
    name: str | None = Field(
        None,
        description='Identificador del deudor final',
        examples=['Empresa XYZ'],
        max_length=140,
    )
    address: str | None = Field(
        None,
        description='Dirección del deudor final',
        examples=['Avenida providencia 345, Las Condes'],
        max_length=256,
    )


class Links(BaseModel):
    """
    Referencias a otros recursos de la API solicitada
    """

    self: str | None = Field(
        None,
        description='URL de la página actual de registros',
        examples=['https://api-chile.cl/accounts/v1/accounts?page=4&pageSize=20'],
        max_length=2000,
        min_length=5,
    )
    first: str | None = Field(
        None,
        description='URL de la primera página de registros',
        examples=['https://api-chile.cl/accounts/v1/accountspage=1&pageSize=20'],
        max_length=2000,
        min_length=5,
    )
    prev: str | None = Field(
        None,
        description='URL de la página anterior de registros',
        examples=['https://api-chile.cl/accounts/v1/accounts?page=3&pageSize=20'],
        max_length=2000,
        min_length=5,
    )
    next: str | None = Field(
        None,
        description='URL de la próxima página de registros',
        examples=['https://api-chile.cl/accounts/v1/accounts?page=5&pageSize=20'],
        max_length=2000,
        min_length=5,
    )
    last: str | None = Field(
        None,
        description='URL da última página de registros',
        examples=['https://api-chile.cl/accounts/v1/accounts?page=13&pageSize=20'],
        max_length=2000,
        min_length=5,
    )


class Meta(BaseModel):
    """
    Meta información sobre los datos solicitados
    """

    firstAvailableDateTime: AwareDatetime = Field(
        ...,
        description='Fecha del primer registro encontrado',
        examples=['2024-01-11 14:56:34'],
    )
    lastAvailableDateTime: AwareDatetime = Field(
        ...,
        description='Fecha del último registro encontrado',
        examples=['2025-01-23 14:56:34'],
    )
    totalPages: int = Field(
        ...,
        description='Total de páginas para los registros encontrados',
        examples=[12],
    )


class Error(BaseModel):
    code: str = Field(
        ...,
        description='Código de error específico de la solicitud',
        examples=['50001'],
        max_length=255,
    )
    title: str = Field(
        ...,
        description='Título legible por un humano de este error en específico',
        examples=['Conexión interrumpida'],
        max_length=255,
    )
    detail: str = Field(
        ...,
        description='Descripción legible por un humano de este error en especifico',
        examples=[
            'No pudimos conectar con el servidor de datos abiertos. Por favor, verifica tu conexión a internet o contáctanos si el problema persiste.'
        ],
        max_length=2048,
    )


class Meta1(BaseModel):
    """
    Meta de información sobre la API solicitada
    """

    requestDateTime: AwareDatetime = Field(
        ...,
        description='Fecha y hora de la consulta, según especificación RFC-3339, formato UTC.',
        examples=['2023-10-09T14:10:00Z'],
        max_length=20,
        min_length=20,
        pattern='^[2-9]\\d{3}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$',
    )


class ResponseErrorMetaSingle(BaseModel):
    errors: list[Error] = Field(..., max_length=13, min_length=1)
    meta: Meta1 | None = Field(
        None, description='Meta de información sobre la API solicitada'
    )


class Error1(BaseModel):
    code: str = Field(
        ...,
        description='Código de error específico',
        examples=['20001'],
        max_length=255,
    )
    title: str = Field(
        ...,
        description='Título legible por un humano de este error en específico',
        examples=['Error al obtener cuentas'],
        max_length=255,
    )
    detail: str = Field(
        ...,
        description='Descripción legible por un humano de este error en específico',
        examples=['La información sobre cuentas no está disponible actualmente.'],
        max_length=2048,
    )


class ResponseError(BaseModel):
    errors: list[Error1] = Field(..., max_length=13, min_length=1)
    meta: Meta1 | None = Field(
        None, description='Meta de información sobre la API solicitada'
    )


class Accounts(BaseModel):
    accountId: str = Field(
        ...,
        description='Identificador de la Cuenta',
        examples=['ACC123456'],
        max_length=40,
    )
    accountType: str = Field(
        ..., description='Tipo de Cuenta', examples=['CACC'], max_length=70
    )
    nickname: str | None = Field(
        None,
        description='Apodo de la Cuenta',
        examples=['Cuenta Sueldo'],
        max_length=70,
    )
    status: str = Field(
        ..., description='Estado de la Cuenta', examples=['Habilitado'], max_length=70
    )
    currency: str = Field(
        ...,
        description='Moneda de la Cuenta',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )
    openingDate: date | None = Field(
        None,
        description='Fecha de Apertura',
        examples=['2025-02-24'],
        pattern='^\\d{4}-\\d{2}-\\d{2}$',
    )
    ownerName: str | None = Field(
        None, description='Nombre del Titular', examples=['Juan Pérez'], max_length=140
    )
    branch: str | None = Field(
        None, description='Sucursal', examples=['Sucursal Centro'], max_length=70
    )
    productName: str = Field(
        ...,
        description='Nombre Comercial del Producto',
        examples=['Cuenta Corriente VIP'],
        max_length=140,
    )
    conditions: list[Conditions] | None = None


class DataBalance(BaseModel):
    currentBalance: CurrentBalance
    balances: list[Balances] | None = None


class DataCurrentOverdraft(BaseModel):
    currentOverdraftLimit: CurrentOverdraftLimit


class DataOverdraft(BaseModel):
    overdraftLimits: list[OverdraftLimit] | None = None


class Transactions(BaseModel):
    transactionID: str = Field(
        ...,
        description='Identificador de la transacción',
        examples=['TXN987654'],
        max_length=40,
    )
    bookingDateTime: AwareDatetime = Field(
        ...,
        description='Fecha/hora de la transacción, formato ISODateTime',
        examples=['2025-02-10T10:00:00Z'],
    )
    transactionsType: str = Field(
        ..., description='Tipo de transacción', examples=['Débito'], max_length=40
    )
    amount: float = Field(
        ..., description='Monto de la transacción', examples=['250000']
    )
    currency: str = Field(
        ...,
        description='Moneda de la transacción',
        examples=['CLP'],
        max_length=3,
        min_length=3,
    )
    paymentPurposeCode: str | None = Field(
        None,
        description='Descripción del pago',
        examples=['Pago de luz'],
        max_length=256,
    )
    categoryPurposeCode: str | None = Field(
        None,
        description='Categoría del pago',
        examples=['Servicios básicos'],
        max_length=256,
    )
    merchantDetails: MerchantDetails | None = None
    debtor: Debtor | None = None
    cardInstruments: list[CardInstrument] | None = None
    creditor: Creditor | None = None
    ultimateCreditor: UltimateCreditor | None = None
    ultimateDebtor: UltimateDebtor | None = None
    balanceAfter: float | None = Field(
        None, description='Saldo Posterior', examples=['10000']
    )


class DataAccounts(BaseModel):
    accounts: list[Accounts] | None = None


class DataAccountSingle(BaseModel):
    account: Accounts


class BalanceResponse(BaseModel):
    data: DataBalance
    links: Links
    meta: Meta


class CourrentOverdraftLimitResponse(BaseModel):
    data: DataCurrentOverdraft
    links: Links
    meta: Meta


class OverdraftResponse(BaseModel):
    data: DataOverdraft
    links: Links
    meta: Meta


class DataTransactions(BaseModel):
    transactions: list[Transactions] | None = None


class AccountsResponse(BaseModel):
    data: DataAccounts
    links: Links
    meta: Meta


class AccountResponse(BaseModel):
    data: DataAccountSingle
    links: Links
    meta: Meta


class TransactionsResponse(BaseModel):
    data: DataTransactions
    links: Links
    meta: Meta
